extends Node2D

const PLAYER_SCENE := preload("res://scenes/player.tscn")
const NPC_SCENE := preload("res://scenes/npc.tscn")
# Offline snapshot of the `npcs` table, regenerated by `bun run npcs:bake`.
const NPC_FALLBACK_PATH := "res://npcs.json"

const DAY_NIGHT_SCENES := ["village", "open_world"]
const COLOR_NIGHT := Color(0.62, 0.66, 0.9)
const COLOR_DAY := Color(1, 1, 1)
const COLOR_DUSK := Color(1.0, 0.87, 0.74)

# Village theme tints (id -> colour). Applied as the world's modulate, which
# multiplies with the day/night CanvasModulate so the two compose. Keep the ids
# in sync with VILLAGE_THEMES on the server. "" is the default (no tint).
const VILLAGE_THEMES := {
	"autumn": Color(1.0, 0.82, 0.55),
	"blossom": Color(1.0, 0.78, 0.86),
	"verdant": Color(0.74, 0.95, 0.72),
	"dusk": Color(0.72, 0.66, 0.95),
}

var remote_players: Dictionary = {}
var _local_player = null
var _day_night: CanvasModulate

func _ready() -> void:
	global.player_in_range = false
	_setup_day_night()
	setup_multiplayer()
	_apply_village_theme(NetworkManager.current_lobby_theme)
	NetworkManager.lobby_theme_changed.connect(_apply_village_theme)

func _apply_village_theme(theme: String) -> void:
	modulate = VILLAGE_THEMES.get(theme, Color.WHITE)

func _setup_day_night() -> void:
	if not DAY_NIGHT_SCENES.has(_network_scene_name()):
		return
	_day_night = CanvasModulate.new()
	add_child(_day_night)
	_apply_day_night()
	var timer := Timer.new()
	timer.wait_time = 5.0
	timer.autostart = true
	timer.timeout.connect(_apply_day_night)
	add_child(timer)

func _apply_day_night() -> void:
	var td := Time.get_time_dict_from_system()
	var h := float(td.hour) + float(td.minute) / 60.0 + float(td.second) / 3600.0
	_day_night.color = _day_night_color(h)

func _day_night_color(h: float) -> Color:
	if h < 5.0 or h >= 21.0:
		return COLOR_NIGHT
	if h < 7.0:
		return COLOR_NIGHT.lerp(COLOR_DAY, (h - 5.0) / 2.0)
	if h < 17.0:
		return COLOR_DAY
	if h < 19.0:
		return COLOR_DAY.lerp(COLOR_DUSK, (h - 17.0) / 2.0)
	return COLOR_DUSK.lerp(COLOR_NIGHT, (h - 19.0) / 2.0)

func _network_scene_name() -> String:
	return scene_file_path.get_file().get_basename()

# Every NPC in a world used to be a hand-placed node in its .tscn, so adding one
# meant opening the Godot editor and shipping a build. They're rows in the `npcs`
# table now, authored from the dashboard, and instanced here on load.
#
# Worlds must `await` this in _ready() before anything that walks their NPC
# children (village.gd's _spawn_npcs/_reveal_trial_npcs, open_world.gd's
# _sync_trial_givers), otherwise those run against an empty tree.
func spawn_world_npcs() -> void:
	var world := _network_scene_name()
	var rows := await _fetch_npcs(world)
	if rows.is_empty():
		# Signed out, offline, or the server errored. The committed bake keeps a
		# world populated instead of dropping the player into an empty town.
		rows = _load_npc_fallback(world)
	for row in rows:
		if typeof(row) == TYPE_DICTIONARY:
			_add_npc(row)

func _fetch_npcs(world: String) -> Array:
	if NetworkManager.session_token == "":
		return []
	var req := HTTPRequest.new()
	add_child(req)
	var url := NetworkManager.SERVER_HTTP_URL + "/api/npcs?world=" + world.uri_encode() \
		+ "&token=" + NetworkManager.session_token.uri_encode()
	if req.request(url) != OK:
		req.queue_free()
		return []
	var res: Array = await req.request_completed
	req.queue_free()
	if int(res[1]) != 200:
		return []
	var body: PackedByteArray = res[3]
	if body.size() == 0:
		return []
	var json = JSON.parse_string(body.get_string_from_utf8())
	if typeof(json) != TYPE_DICTIONARY or not json.get("ok", false):
		return []
	var npcs = json.get("npcs", [])
	return npcs if typeof(npcs) == TYPE_ARRAY else []

func _load_npc_fallback(world: String) -> Array:
	if not FileAccess.file_exists(NPC_FALLBACK_PATH):
		return []
	var json = JSON.parse_string(FileAccess.get_file_as_string(NPC_FALLBACK_PATH))
	if typeof(json) != TYPE_DICTIONARY:
		return []
	var rows = json.get(world, [])
	return rows if typeof(rows) == TYPE_ARRAY else []

# Exports are set before add_child so npc.gd's _ready() (which reads position for
# its wander home, and skin for its spriteframes) sees the authored values.
func _add_npc(row: Dictionary) -> void:
	var inst = NPC_SCENE.instantiate()
	inst.npc_name = String(row.get("npc_name", "Villager"))
	inst.name = inst.npc_name
	inst.position = Vector2(float(row.get("pos_x", 0.0)), float(row.get("pos_y", 0.0)))
	inst.skin = String(row.get("skin", "cvc:1"))
	inst.custom_hair = String(row.get("custom_hair", ""))
	inst.custom_sheet = String(row.get("custom_sheet", ""))
	inst.dialogue = String(row.get("dialogue", ""))
	inst.opens_projects = bool(row.get("opens_projects", false))
	inst.opens_explore = bool(row.get("opens_explore", false))
	inst.quest_project = bool(row.get("quest_project", false))
	inst.faq = bool(row.get("faq", false))
	inst.quest_trial = bool(row.get("quest_trial", false))
	inst.trial_checkin = bool(row.get("trial_checkin", false))
	inst.trial_name = String(row.get("trial_name", ""))
	inst.quest_offer = String(row.get("quest_offer", ""))
	inst.quest_done = String(row.get("quest_done", ""))
	inst.trial_reminder = String(row.get("trial_reminder", ""))
	inst.wanders = bool(row.get("wanders", true))
	inst.speed = float(row.get("speed", 50.0))
	inst.wander_radius = float(row.get("wander_radius", 56.0))
	inst.min_wait = float(row.get("min_wait", 1.2))
	inst.max_wait = float(row.get("max_wait", 4.5))
	# A check-in copy stays hidden until its world confirms the Trial is live;
	# npc.gd's _ready() also de-monitors its InteractArea when it starts hidden.
	if inst.trial_checkin:
		inst.visible = false
	add_child(inst)

func setup_multiplayer() -> void:
	if not NetworkManager.is_connected_to_server():
		_spawn_local(_default_spawn())
		return
	NetworkManager.scene_init.connect(_on_scene_init)
	NetworkManager.player_joined.connect(_on_player_joined)
	NetworkManager.player_moved.connect(_on_player_moved)
	NetworkManager.player_left.connect(_on_player_left)
	NetworkManager.player_skin_changed.connect(_on_player_skin_changed)
	NetworkManager.chat_message.connect(_on_chat)
	NetworkManager.emote_received.connect(_on_emote)
	NetworkManager.send_scene_change(_network_scene_name())
	await get_tree().create_timer(5.0).timeout
	if not is_instance_valid(_local_player):
		_spawn_local(_default_spawn())

func _unhandled_input(event: InputEvent) -> void:
	if not (event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_LEFT):
		return
	if ChatHud.is_typing() or Dialogue.is_open or global.ui_blocked():
		return
	var mp := get_global_mouse_position()
	var best_id := ""
	var best_d := 22.0
	for uid in remote_players:
		var rp = remote_players[uid]
		if not is_instance_valid(rp):
			continue
		var d: float = rp.global_position.distance_to(mp)
		if d < best_d:
			best_d = d
			best_id = uid
	if best_id != "":
		ProfileHud.open(best_id)
		get_viewport().set_input_as_handled()

func _default_spawn() -> Vector2:
	var marker = get_node_or_null(global.spawn_point)
	if marker == null:
		marker = get_node_or_null("PlayerSpawn")
	return marker.global_position if marker else Vector2.ZERO

func _spawn_local(pos: Vector2) -> void:
	if is_instance_valid(_local_player):
		_local_player.global_position = pos
		Loader.hide_loading()
		return
	var p = PLAYER_SCENE.instantiate()
	p.z_index = 10
	p.is_local = true
	p.global_position = pos
	add_child(p)
	_local_player = p
	Loader.hide_loading()

func _on_scene_init(your_id: String, your_pos: Vector2, others: Array, spawn_at_default: bool) -> void:
	if spawn_at_default:
		your_pos = _default_spawn()
	_spawn_local(your_pos)
	var seen := {}
	for p in others:
		var uid := String(p["userId"])
		if uid == your_id:
			continue
		seen[uid] = true
		_spawn_remote(uid, String(p["displayName"]), Vector2(p["posX"], p["posY"]), String(p.get("skin", "cvc:1")))
	for uid in remote_players.keys():
		if not seen.has(uid):
			_despawn_remote(uid)

func _on_player_joined(user_id: String, name: String, pos: Vector2, _direction: String, skin: String) -> void:
	if user_id == NetworkManager.user_id:
		return
	_spawn_remote(user_id, name, pos, skin)

func _on_player_moved(user_id: String, pos: Vector2, direction: String) -> void:
	if remote_players.has(user_id):
		remote_players[user_id].remote_update(pos, direction)

func _on_player_left(user_id: String) -> void:
	_despawn_remote(user_id)

func _on_player_skin_changed(user_id: String, skin: String) -> void:
	if user_id == NetworkManager.user_id:
		if is_instance_valid(_local_player):
			_local_player.set_skin(skin)
	elif remote_players.has(user_id):
		remote_players[user_id].set_skin(skin)

func _spawn_remote(user_id: String, name: String, pos: Vector2, skin: String = "cvc:1") -> void:
	if remote_players.has(user_id):
		remote_players[user_id].remote_update(pos, remote_players[user_id].current_dir)
		return
	var node = PLAYER_SCENE.instantiate()
	node.z_index = 10
	node.is_local = false
	node.player_name = name
	node.skin = skin
	node.global_position = pos
	add_child(node)
	remote_players[user_id] = node

func _on_chat(user_id: String, _display_name: String, text: String) -> void:
	var node = _local_player if user_id == NetworkManager.user_id else remote_players.get(user_id)
	if is_instance_valid(node):
		node.show_chat_bubble(text)

func _on_emote(user_id: String, key: String) -> void:
	var node = _local_player if user_id == NetworkManager.user_id else remote_players.get(user_id)
	if is_instance_valid(node):
		node.show_emote(key)

func _despawn_remote(user_id: String) -> void:
	if remote_players.has(user_id):
		remote_players[user_id].queue_free()
		remote_players.erase(user_id)
