-- Free-form internal notes reviewers can leave on any project - not tied to
-- a verdict, just context for whoever looks at this project next ("player
-- already warned about this in Slack", "double-check the demo link", etc.).
-- Shown on the dashboard's project detail page and the review page (see
-- listProjectNotes/addProjectNote in apps/dashboard/lib/db.ts +
-- app/actions.ts). Modeled on review_audits (0012_review_audit.sql).
--
-- Idempotent. Run in psql against the orchard/CNPG database.

CREATE TABLE IF NOT EXISTS "project_notes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
  "author" text NOT NULL,
  "body" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_project_notes_project" ON "project_notes"("project_id");
