-- Minimal stand-in for the tables 0183_operations.sql reads or extends, so the
-- operations SQL can be exercised against a real Postgres in isolation. Only
-- the columns those functions and the evidence code touch, kept in step with
-- the real migrations (0009 project_journals, 0020/0023 pixels, 0081
-- collaborators).
CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  display_name text NOT NULL DEFAULT '',
  slack_id text,
  hackatime_token text,
  pixels bigint NOT NULL DEFAULT 0,
  oauth_provider text NOT NULL DEFAULT 'test'
);
CREATE TABLE projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'draft',
  banned_at timestamptz,
  hackatime_projects text[] NOT NULL DEFAULT '{}'
);
CREATE TABLE project_collaborators (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'accepted',
  hackatime_projects text[] NOT NULL DEFAULT '{}',
  UNIQUE (project_id, user_id)
);
CREATE TABLE project_journals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  hours real NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE pixel_transactions (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_id bigint REFERENCES projects(id) ON DELETE SET NULL,
  amount bigint NOT NULL,
  hours numeric(10, 2) NOT NULL DEFAULT 0,
  reason text NOT NULL DEFAULT '',
  created_by text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
