import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { listNpcs, type NpcRow, type SidequestRow } from "@/lib/db";
import { addNpc, updateNpc, toggleNpc, deleteNpc } from "@/app/actions";
import { NpcForm, type NpcDraft } from "@/app/_components/NpcForm";
import { PendingButton } from "@/app/_components/PendingButton";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";

const WORLD_LABEL: Record<string, string> = {
  village: "The Hub village",
  open_world: "Open world (Dustline)",
  factory_island: "Factory Island",
  pixel_cafe: "Pixl Cafe",
};

// npc.gd resolves its modes as an if/elif chain, in this order. Reading a row
// back into a single "kind" has to follow the same precedence, or the form would
// show a different mode than the game actually runs.
function kindOf(n: NpcRow): string {
  if (n.opens_projects) return "projects";
  if (n.opens_explore) return "explore";
  if (n.quest_trial) return "trial";
  if (n.quest_project) return "project_quest";
  if (n.faq) return "faq";
  return "dialogue";
}

const KIND_LABEL: Record<string, string> = {
  dialogue: "talks",
  trial: "Trial-giver",
  projects: "opens Terminal",
  explore: "opens Explore",
  project_quest: "asks for a project",
  faq: "answers FAQs",
};

function toDraft(n: NpcRow): NpcDraft {
  return {
    id: n.id,
    world: n.world,
    pos_x: n.pos_x,
    pos_y: n.pos_y,
    npc_name: n.npc_name,
    skin: n.skin,
    dialogue: n.dialogue,
    kind: kindOf(n),
    trial_checkin: n.trial_checkin,
    sidequest_id: n.sidequest_id,
    quest_offer: n.quest_offer,
    quest_done: n.quest_done,
    trial_reminder: n.trial_reminder,
    wanders: n.wanders,
  };
}

interface Bounds {
  x: number;
  y: number;
  w: number;
  h: number;
}

// Generated by `bun run map:sync` from the game's baked world maps. Read off
// disk rather than fetched, so the picker renders on the first server pass.
async function loadBounds(): Promise<Record<string, Bounds>> {
  try {
    const raw = await readFile(
      join(process.cwd(), "public", "map", "bounds.json"),
      "utf8",
    );
    return (JSON.parse(raw).worlds ?? {}) as Record<string, Bounds>;
  } catch {
    return {};
  }
}

export async function NpcsTab({ quests }: { quests: SidequestRow[] }) {
  const [npcs, bounds] = await Promise.all([listNpcs(), loadBounds()]);

  const trials = quests.map((q) => ({ id: q.id, name: q.name, active: q.active }));
  const trialById = new Map(quests.map((q) => [q.id, q]));
  // Enough per marker to answer "what does that one do?" from the map itself,
  // without scrolling down to find its card.
  const markers = npcs.map((n) => {
    const t = n.sidequest_id ? trialById.get(n.sidequest_id) : null;
    return {
      id: n.id,
      world: n.world,
      npc_name: n.npc_name,
      pos_x: n.pos_x,
      pos_y: n.pos_y,
      kind: kindOf(n),
      skin: n.skin,
      trial: t && t.active ? t.name : null,
      dialogue: n.dialogue,
      active: n.active,
    };
  });
  const worlds = Object.keys(WORLD_LABEL).filter((w) =>
    npcs.some((n) => n.world === w),
  );

  const broken = npcs.filter((n) => {
    if (kindOf(n) !== "trial") return false;
    const t = n.sidequest_id ? trialById.get(n.sidequest_id) : null;
    return !t || !t.active;
  });

  return (
    <div className="space-y-8">
      <p className="text-sm text-muted-foreground max-w-2xl">
        Everyone standing around in the game world. The client spawns these on load, so
        adding or moving one takes effect without shipping a new build. Click the map to
        place them.
      </p>

      {Object.keys(bounds).length === 0 && (
        <Alert variant="destructive">
          <AlertDescription className="font-medium text-destructive">
            No world maps found. Run <code>bun run map:sync</code> to copy them out of the
            game project, otherwise the spot-picker has nothing to draw.
          </AlertDescription>
        </Alert>
      )}

      {broken.length > 0 && (
        <Alert variant="destructive">
          <AlertDescription className="font-medium text-destructive">
            {broken.length === 1 ? "1 Trial-giver has" : `${broken.length} Trial-givers have`}{" "}
            no usable Trial ({broken.map((n) => n.npc_name).join(", ")}). The game only
            offers Trials that are active, so these fall back to plain dialogue in-game.
          </AlertDescription>
        </Alert>
      )}

      <Card className="p-5 md:p-6 gap-0">
        <div className="text-base font-semibold mb-4">Add an NPC</div>
        <NpcForm
          action={addNpc}
          bounds={bounds}
          trials={trials}
          others={markers}
          submitLabel="Add NPC"
          pendingLabel="Adding…"
        />
      </Card>

      {worlds.map((world) => (
        <div key={world} className="space-y-3">
          <div className="text-base font-semibold">{WORLD_LABEL[world]}</div>
          {npcs
            .filter((n) => n.world === world)
            .map((n) => {
              const kind = kindOf(n);
              const trial = n.sidequest_id ? trialById.get(n.sidequest_id) : null;
              const brokenTrial = kind === "trial" && (!trial || !trial.active);
              return (
                <Card key={n.id} className={`p-4 gap-0 ${n.active ? "" : "opacity-60"}`}>
                  <div className="flex items-start justify-between gap-3 flex-wrap">
                    <div className="min-w-0">
                      <div className="font-bold flex items-center gap-2 flex-wrap">
                        {n.npc_name}
                        <Badge variant="secondary">{KIND_LABEL[kind]}</Badge>
                        {n.trial_checkin && <Badge variant="secondary">check-in</Badge>}
                        {!n.active && <Badge variant="secondary">hidden</Badge>}
                        {brokenTrial && (
                          <Badge variant="destructive">
                            {trial ? "Trial is hidden" : "no Trial linked"}
                          </Badge>
                        )}
                      </div>
                      <div className="text-xs text-muted-foreground mt-1 tabular-nums">
                        ({Math.round(n.pos_x)}, {Math.round(n.pos_y)}) · {n.skin}
                        {trial ? ` · ${trial.name}` : ""}
                        {n.wanders ? " · wanders" : ""}
                      </div>
                      {n.dialogue && (
                        <div className="text-sm text-muted-foreground mt-1 line-clamp-2">
                          {n.dialogue}
                        </div>
                      )}
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <form action={toggleNpc}>
                        <input type="hidden" name="id" value={n.id} />
                        <input type="hidden" name="active" value={n.active ? "0" : "1"} />
                        <PendingButton
                          variant="outline"
                          size="sm"
                          pendingText={n.active ? "Hiding…" : "Showing…"}
                        >
                          {n.active ? "Hide" : "Show"}
                        </PendingButton>
                      </form>
                      <form action={deleteNpc}>
                        <input type="hidden" name="id" value={n.id} />
                        <PendingButton
                          variant="outline"
                          size="sm"
                          pendingText="Deleting…"
                          confirm={`Delete ${n.npc_name}? They'll vanish from the world on the next load.`}
                          className="text-rose-600 border-rose-200 dark:border-rose-500/30 hover:bg-rose-50 dark:hover:bg-rose-500/10 hover:text-rose-600"
                        >
                          Delete
                        </PendingButton>
                      </form>
                    </div>
                  </div>

                  <details className="w-full mt-3 border-t pt-3">
                    <summary className="text-sm cursor-pointer select-none text-muted-foreground hover:text-foreground">
                      Edit
                    </summary>
                    <div className="mt-3">
                      <NpcForm
                        action={updateNpc}
                        bounds={bounds}
                        trials={trials}
                        others={markers}
                        initial={toDraft(n)}
                        submitLabel="Save changes"
                        pendingLabel="Saving…"
                      />
                    </div>
                  </details>
                </Card>
              );
            })}
        </div>
      ))}

      {npcs.length === 0 && (
        <Card className="p-8 text-center text-muted-foreground text-sm">
          No NPCs yet. The world will be empty until you add one.
        </Card>
      )}
    </div>
  );
}
