import { Router } from "express";
import { timingSafeEqual } from "node:crypto";
import { supabase } from "../db/client.js";
import { rateLimit } from "../rateLimit.js";

const router = Router();

// Public, no-login page for one project's journal entries only (see
// journal_share_token on projects, generated by ensureJournalShareToken in
// apps/dashboard/lib/db.ts, and put into the "Justification - Alternate
// Tracking Method" Airtable field on approval). Deliberately its own tiny
// endpoint rather than reusing /api/explore/projects/:id - that one exposes
// repo/demo links, description, etc.; this exposes journals and nothing
// else, keyed by a long random token instead of the player's session.
const journalsLimiter = rateLimit({ windowMs: 60_000, max: 30, name: "journals_public" });

function safeTokenEquals(a: string, b: string): boolean {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  // timingSafeEqual throws on a length mismatch rather than returning false -
  // guard it first. Leaking whether the length matches isn't a meaningful
  // risk (the real secret is the token's content, all issued at one fixed
  // length), just enough to avoid a runtime crash on a mismatched guess.
  if (bufA.length !== bufB.length) return false;
  return timingSafeEqual(bufA, bufB);
}

// #public, no session - the whole point of this route.
router.get("/api/journals/public/:projectId/:token", journalsLimiter, async (req, res) => {
  const projectId = Number(req.params.projectId);
  const token = String(req.params.token ?? "");
  if (!Number.isFinite(projectId) || !token) return res.status(404).json({ ok: false });

  const { data: project, error: projectError } = await supabase
    .from("projects")
    .select("id, name, journal_share_token")
    .eq("id", projectId)
    .maybeSingle();
  if (projectError) {
    console.error("[journals-public] project lookup failed", projectError);
    return res.status(500).json({ ok: false });
  }
  // Same 404 whether the project doesn't exist, has no token yet, or the
  // token just doesn't match - never confirm a project id is valid to an
  // unauthenticated caller with the wrong token.
  if (!project?.journal_share_token || !safeTokenEquals(project.journal_share_token as string, token))
    return res.status(404).json({ ok: false });

  const { data: journals, error: journalsError } = await supabase
    .from("project_journals")
    .select("id, title, content, hours, approved_hours, created_at, user_id")
    .eq("project_id", projectId)
    .order("created_at", { ascending: true });
  if (journalsError) {
    console.error("[journals-public] journals lookup failed", journalsError);
    return res.status(500).json({ ok: false });
  }

  const userIds = [...new Set((journals ?? []).map((j) => j.user_id as string))];
  const contributorNames = new Map<string, string>();
  if (userIds.length > 0) {
    const { data: users } = await supabase
      .from("users")
      .select("id, display_name")
      .in("id", userIds);
    for (const u of users ?? [])
      contributorNames.set(u.id as string, (u.display_name as string) || "a builder");
  }

  res.json({
    ok: true,
    project: { name: project.name },
    // Only surface one contributor name when there's more than one - a
    // solo project's page shouldn't imply anyone else worked on it.
    multiContributor: userIds.length > 1,
    journals: (journals ?? []).map((j) => ({
      id: j.id,
      title: j.title,
      content: j.content,
      hours: j.hours,
      approvedHours: j.approved_hours,
      createdAt: j.created_at,
      contributor: contributorNames.get(j.user_id as string) ?? null,
    })),
  });
});

export default router;
